"""Add meetings table

Revision ID: 06be5889e062
Revises: 9c67841b6625
Create Date: 2026-04-29 11:09:12.384304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06be5889e062'
down_revision: Union[str, Sequence[str], None] = '9c67841b6625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposer_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('proposer_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='proposal_status', create_constraint=True), nullable=False),
    sa.Column('receiver_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='proposal_status', create_constraint=True), nullable=False),
    sa.Column('source', sa.Enum('USER', 'ENGINE', name='meeting_source', create_constraint=True), nullable=False),
    sa.Column('meeting_type', sa.Enum('COFFEEBREAK', 'OTHER', name='meeting_type', create_constraint=True), nullable=False),
    sa.Column('proposed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_proposer_id'), 'meetings', ['proposer_id'], unique=False)
    op.create_index(op.f('ix_meetings_receiver_id'), 'meetings', ['receiver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_receiver_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_proposer_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
